version: "3.8"

services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=prince
      - DB_PASSWORD=123
      - DB_NAME=gokap
    command: "npm run dev"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: gokap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
